### ISSUE TITLE
Doesn't build today

### ISSUE THREAD

**Issue by quicklisp** [Shinmera/flare#1]
Not sure what the issue is, here is the log: http://report.quicklisp.org/2016-07-25/failure-report/flare.html#flare

    ;     (FOR-MINIMAL:FOR ((FOR-ITERATOR:CURRENT FLARE-QUEUE:IN-QUEUE
    ;                                             FLARE-QUEUE:QUEUE)
    ;                       (FLARE-QUEUE::I FOR-MINIMAL:FROM 0))
    ;       (WHEN (= FLARE-QUEUE::I FLARE-QUEUE::N)
    ;         (RETURN (VALUES FOR-ITERATOR:CURRENT T))))
    ; --> FOR:WITH-INTERLEAVING FOR:WITH-INTERLEAVING LET* FOR:WITH-INTERLEAVING 
    ; ==>
    ;   (LET* ((#:FROM518 0)
    ;          (#:TO519 NIL)
    ;          (#:BY520 1)
    ;          (#:ASCENDING517 (OR (NOT #:TO519) (< #:FROM518 #:TO519)))
    ;          (FLARE-QUEUE::I
    ;           (IF #:ASCENDING517
    ;               (- #:FROM518 #:BY520)
    ;               (+ #:FROM518 #:BY520))))
    ;     (DECLARE (IGNORABLE #:ASCENDING517 #:FROM518 #:TO519 #:BY520))
    ;     (DECLARE (TYPE REAL FLARE-QUEUE::I))
    ;     (DECLARE (TYPE REAL #:FROM518))
    ;     (DECLARE (TYPE REAL #:TO519))
    ;     (DECLARE (TYPE REAL #:BY520))
    ;     (DECLARE (TYPE BOOLEAN #:ASCENDING517))
    ;     (FOR::WITH-FOR-BLOCK NIL
    ;       (FOR::WITH-FOR-TAGBODY (PROGN
    ;                               (LET #
    ;                                 #)
    ;                               (INCF FLARE-QUEUE::I #:BY520)
    ;                               (WHEN # #))
    ;         (FOR-MINIMAL:RETURN-FOR))))
    ; 
    ; caught WARNING:
    ;   Constant NIL conflicts with its asserted type REAL.
    ;   See also:
    ;     The SBCL Manual, Node "Handling of Types"

**Comment by Shinmera** [comment]
I think this might come from an outdated version of For. I can't reproduce it with up-to-date sources here.

**Comment by quicklisp** [comment]
I am using the most recent version of both. Do you get an error if you load with quickload :verbose t, or with asdf directly?

**Comment by Shinmera** [comment]
Ah, indeed, verbose shows the problem. I'll debug it asap.

**Comment by Shinmera** [comment]
That should do it. Thanks for  the report!
